### ISSUE TITLE
Multi-az recovery fails due to launch-id being the same

### ISSUE THREAD

**Issue by analytically** [aws-quickstart/quickstart-confluent-kafka#44]
Probably due to: https://github.com/aws-quickstart/quickstart-confluent-kafka/blob/660477609b6b43a3dafcf22d7f709b65088863be/templates/nodegroup.template#L807

I'm unsure how to resolve this.

**Comment by analytically** [comment]
OTOH the AMI launch index is only really useful when you are launching multiple instances together in one request, which a ASG with LC isn't doing upon recovery.

**Comment by dbtucker** [comment]
Can you be more specific about the meaning of "multi-az recovery fails" ?   

The internal logic for tagging instances is simply window dressing.   The order of hosts in the output files (/tmp/cphosts) is the determining factor.   In fact, that ami_launch_index value is not even used UNLESS the explicit listing of hosts in the deployment has failed.

**Comment by analytically** [comment]
"multi-az recovery fails" -> I have specified multiple (private) subnets, and when terminating an instance (after CF brought the stack up) the recovered instance has no tags.

**Comment by analytically** [comment]
Eg. the recovered instance has `dev-kafka-broker-2` while a  `dev-kafka-broker-2` already exists in a different subnet.

**Comment by dbtucker** [comment]
So, the scenario is 
   1. Launch a cluster with CF ... 3 brokers (ignore other roles for now)
   2. Cluster comes up, three instances tagged as broker-0, broker-1, and broker-2
   3. Terminate broker-1 manually
   4. Auto-scaling group behavior results in new instance being launched
   5. That new instance is tagged with "broker-2", resulting in confusion with the "broker-2" from the initial deployment.

Is that a correct summary ?

**Comment by analytically** [comment]
Correct indeed.

**Comment by dbtucker** [comment]
The issue is in the "gen-cluster-hosts.sh" logic.   Instances that are "running" or "stopped" are counted, but the "terminated" ones are not.

I'm not sure there's a way to fix that logic.   If the "terminated" state was included, it would only resolve the very specific use case you describe.   If you terminated a 2nd instance a day later (when the original "terminated" instance was no longer reported by the describe-instances command, we'd encounter the same problem.

I'll investigate whether there is a command that could be used against the auto-scaling group that might be more appropriate.

**Comment by analytically** [comment]
Changing the shutdown behaviour to 'stop' might help as well.

**Comment by dbtucker** [comment]
Closed to track with #46
