### ISSUE TITLE
Scaling number of brokers

### ISSUE THREAD

**Issue by agusc** [aws-quickstart/quickstart-confluent-kafka#48]
### Context

I've deployed the quickstart confluent kafka setup using the `confluent-kafka-master.template` template ie deployed to a new VPC.
After a while running the cluster I've found I need to increase the broker capacity, just the number of running brokers from the current 5 to 7.

### Question

What would be the easiest way to scale the number of running brokers on an already deployed stack? Is it even possible?

### Efforts tried so far

I've tried creating a Cloudformation change set for the deployed root stack without success, it failed [1] and rolled back.
Then tried to create the change set to the BrokerStack only, but didn't work out either  [2].

[1] 
The first change set failed on root stack with following error:
```
Logical Id: ConfluentStack
Status reason: Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [BrokerStack]
```

In the nested `ConfluentStack` stack failed with:
```
Logical Id: BrokerStack
Status reason: Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [NodesReadyCondition]
```

And finally in the inner most stack `BrokerStack` reason is:
```
Logical Id: NodesReadyCondition
Status reason: Update to resource type AWS::CloudFormation::WaitCondition is not supported
```

[2]
The second change set failed similarly with just:

```
Logical Id: NodesReadyCondition
Status reason: Update to resource type AWS::CloudFormation::WaitCondition is not supported
```

Any help would be very much appreaciated.

**Comment by agusc** [comment]
I should have looked more in depth, just found the Auto Scaling Groups for all three kind of nodes (Brokers, Workers and Zookeepers)

**Comment by dbtucker** [comment]
@agusc  Glad you drilled down to the individual auto-scaling groups.  

The template was not designed for dynamic scaling ... but the use case you describe (increasing from 5 to 7 brokers by updating the ASG settings) should work just fine.  However, downsizing the set of brokers is not supported.

The same ASG process will work to increase the number of workers.  However, remember that worker0 and worker1 are "special" (worker0 has the Control Center process while worker1 has the schema registry service).   The configuration of each worker assumes that worker1 (as ordered by launch time) is running the Schema Registry service and uses that information in the configuration for the REST Proxy and Connect Worker services.    So you'll want to start with 2 or more workers if you expect that you'll be expanding the total set.

**Comment by agusc** [comment]
Hi @dbtucker, thanks for the additional info.
I'm not planning to scale the workers, I'm good with the 2 nodes I already have but will keep that in mind just in case.

You got me thinking on your comments about downsize the broker count.
I'm expecting current expansion won't be needed after several weeks of usage, wouldn't it be possible to downsize brokers count even if manual action is taken? 

Out of the tip of my head I'm thinking in:

1. removing high storage topics once they are not needed anymore.
2. make sure needed topics (both master and replicas) are only in brokers to be kept.
3. Make ASG downsize with a selected instance.

I don't have AWS console access right now to check on 3 but I guess should be possible, isn't it?

**Comment by dbtucker** [comment]
@agusc   You can absolutely scale back a cluster manually.   In fact, if your topics have the default replication factor of 3, there's no real risk of removing a single node as the cluster will re-replicate data as necessary on the remaining node.  You could take the time to manually move the topic partitions, or simply let the cluster do that rebalance on it's own (there are timeouts after which the cluster will take it upon itself to re-replicate the data).  

It is the case that the manual partition re-assignement will likely be quicker, but it requires that you be a bit more knowledgeable about the data positioning in the cluster (eg if topic partition T4 has replicas on nodes 2, 4, and 7, you'd want to manually move the replica on node 7 to node 1, 3 or 5 ... not 2 or 4).   

The issue is that you want to be careful with removing any other nodes until the data is properly re-replicated.   The Control Center UI will show you "under-replicated topic partitions", and there admin commands you can execute from the command line to get the same information.
